use wkdb;

INSERT INTO `wkdb`.`tbclientes` (`Nome`, `Cidade`, `UF`) VALUES ('José Moura', 'Belo Horizonte', 'MG');
INSERT INTO `wkdb`.`tbclientes` (`Nome`, `Cidade`, `UF`) VALUES ('João da Silva', 'Belo Horizonte', 'MG');
INSERT INTO `wkdb`.`tbclientes` (`Nome`, `Cidade`, `UF`) VALUES ('Joaquim José', 'Rio de Janeiro', 'RJ');
INSERT INTO `wkdb`.`tbclientes` (`Nome`, `Cidade`, `UF`) VALUES ('Francisco Matos', 'Belo Horizonte', 'MG');
INSERT INTO `wkdb`.`tbclientes` (`Nome`, `Cidade`, `UF`) VALUES ('Fernando Fernandes', 'Belo Horizonte', 'MG');
INSERT INTO `wkdb`.`tbclientes` (`Nome`, `Cidade`, `UF`) VALUES ('Mauro Lopes', 'São Paulo', 'SP');
INSERT INTO `wkdb`.`tbclientes` (`Nome`, `Cidade`, `UF`) VALUES ('Roberto da Cunha', 'Vitória', 'ES');
INSERT INTO `wkdb`.`tbclientes` (`Nome`, `Cidade`, `UF`) VALUES ('Irineu Maria', 'Rio de Janeiro', 'RJ');
INSERT INTO `wkdb`.`tbclientes` (`Nome`, `Cidade`, `UF`) VALUES ('Mateus Sousa', 'Vitória', 'ES');
INSERT INTO `wkdb`.`tbclientes` (`Nome`, `Cidade`, `UF`) VALUES ('Guilhermino Fraga', 'Belo Horizonte', 'MG');
INSERT INTO `wkdb`.`tbclientes` (`Nome`, `Cidade`, `UF`) VALUES ('Dileno Silva', 'Belo Horizonte', 'MG');
INSERT INTO `wkdb`.`tbclientes` (`Nome`, `Cidade`, `UF`) VALUES ('Dilton Santos', 'Pedro Leopoldo', 'MG');
INSERT INTO `wkdb`.`tbclientes` (`Nome`, `Cidade`, `UF`) VALUES ('Enzo Sousa', 'Belo Horizonte', 'MG');
INSERT INTO `wkdb`.`tbclientes` (`Nome`, `Cidade`, `UF`) VALUES ('Benício Sousa', 'Belo Horizonte', 'MG');
INSERT INTO `wkdb`.`tbclientes` (`Nome`, `Cidade`, `UF`) VALUES ('Fernanda Sousa', 'Belo Horizonte', 'MG');
INSERT INTO `wkdb`.`tbclientes` (`Nome`, `Cidade`, `UF`) VALUES ('Maria da Silva', 'Belo Horizonte', 'MG');
INSERT INTO `wkdb`.`tbclientes` (`Nome`, `Cidade`, `UF`) VALUES ('Alenir Maria', 'Pedro Leopoldo', 'MG');
INSERT INTO `wkdb`.`tbclientes` (`Nome`, `Cidade`, `UF`) VALUES ('Ivone Santos', 'Pedro Leopoldo', 'MG');
INSERT INTO `wkdb`.`tbclientes` (`Nome`, `Cidade`, `UF`) VALUES ('Sônia Lucia', 'Belo Horizonte', 'MG');
INSERT INTO `wkdb`.`tbclientes` (`Nome`, `Cidade`, `UF`) VALUES ('Luana Reis', 'Vitória', 'ES');
INSERT INTO `wkdb`.`tbclientes` (`Nome`, `Cidade`, `UF`) VALUES ('Joana Prado', 'Belo Horizonte', 'MG');
INSERT INTO `wkdb`.`tbclientes` (`Nome`, `Cidade`, `UF`) VALUES ('Josiani Silva', 'São Paulo', 'SP');
INSERT INTO `wkdb`.`tbclientes` (`Nome`, `Cidade`, `UF`) VALUES ('Renata Cardoso', 'Rio de Janeiro', 'RJ');
INSERT INTO `wkdb`.`tbclientes` (`Nome`, `Cidade`, `UF`) VALUES ('Marina Maia', 'Belo Horizonte', 'MG');
INSERT INTO `wkdb`.`tbclientes` (`Nome`, `Cidade`, `UF`) VALUES ('Fabiana Valente', 'São Paulo', 'SP');
